Description: >
  This template illustrates how to use AWS CodeBuild and AWS CodePipeline to
  achieve continuous deployment of source code from a GitHub repository via a
  Docker container to an Amazon EC2 Container Service cluster.

Parameters:
  Cluster:
    Type: String
    Description: ECS Cluster to deploy on

  S3Bucket:
    Type: String
    Description: Bucket of zipped repo

  SourceS3Key:
    Type: String
    Description: Location of zip file in bucket

Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      Cluster:
        default: "Staging"
      S3Bucket:
        default: ""
      SourceS3Key:
        default: ""
    ParameterGroups:
      - Label:
          default: Configuration
        Parameters:
          - Cluster
          - S3Bucket
          - SourceS3Key

Resources:
  DeploymentPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/arc-ecs-cont-deployment/templates/deployment-pipeline.yaml
      Parameters:
        Cluster: !GetAtt Cluster.Outputs.ClusterName
        S3Bucket: !Ref S3Bucket
        SourceS3Key: !Ref SourceS3Key
        TemplateBucket: !Sub arc-ecs-cont-deployment-${AWS::Region}

Outputs:
  PipelineUrl:
    Description: The continuous deployment pipeline in the AWS Management Console.
    Value: !GetAtt DeploymentPipeline.Outputs.PipelineUrl
