Description: >
  This template is for deploying source code from S3 Bucket to an ECS Cluster

Parameters:
  Cluster:
    Type: String
    Description: ECS Cluster to deploy on

  S3Bucket:
    Type: String
    Description: Bucket of zipped repo

  SourceS3Key:
    Type: String
    Description: Location of zip file in bucket

  TaskDef:
    Type: String
    Description: Name of Task Def file

Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      Cluster:
        default: "ECS Cluster"
      S3Bucket:
        default: "S3 Bucket"
      SourceS3Key:
        default: "S3 File Path"
      TaskDef:
        default: "Task Def"
    ParameterGroups:
      - Label:
          default: Configuration
        Parameters:
          - Cluster
          - S3Bucket
          - SourceS3Key
          - TaskDef

Resources:
  DeploymentPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/arc-ecs-cont-deployment-ap-southeast-2/templates/deployment-pipeline.yaml
      Parameters:
        Cluster: !Ref Cluster
        S3Bucket: !Ref S3Bucket
        SourceS3Key: !Ref SourceS3Key
        TemplateBucket: !Sub arc-ecs-cont-deployment-${AWS::Region}

Outputs:
  PipelineUrl:
    Description: The continuous deployment pipeline in the AWS Management Console.
    Value: !GetAtt DeploymentPipeline.Outputs.PipelineUrl
